### PR TITLE
Switch from angular2-highcharts to highcharts-angular (UA-983)

### PR DESCRIPTION
**Pull request by vcward**
I swapped out the angular2-highcharts dependency for Highcharts' official wrapper for Angular. This should be more reliable and better to maintain in the long run. The data portals should still look and function as it does now.

Angular has also been updated to v. 6. So to test locally:
```
rm -rf node_modules
npm install
npm run start-(project)-dev /* where (project) = uhero, coh, or nta */
```

The builds are also up to date on the staging server.

### CODE REVIEW

**Comment by kotodharma** [comment]
Hate to cause trouble but :=} when I run the NTA portal locally with `npm run start-nta-dev`, the titles on the "thumbnail" boxes (do we have a proper name for these things?) don't seem right. They are repeating the category name in the heading, rather than being the names of geographies.

**Comment by vcward** [comment]
Thanks for catching that. The titles should be correct now for NTA.
For the dependency vulnerability, I think I'll need to put that in another PR. It's a known issue for Angular-CLI (https://github.com/angular/angular-cli/issues/11699); waiting for an update on their end.

**Comment by kotodharma** [comment]
I guess Snyk is not "passing" this PR because of the security issue? I've looked to see if I could just disable Snyk, but can't seem to find where the controls are for that. If you have an idea, lmk. Any idea how long you might have to wait for Angular-CLI to put out a patch?

**Comment by kotodharma** [comment]
I see... the hooks are in per-repo settings... I was just looking in the global settings. Geh. Thanks :=)

**Comment by vcward** [comment]
Ok that didn't do anything. It seems like snyk might not be failing either, but just stuck waiting? I tried deactivating it, but I might need to open a new PR to get right of the check. Let me know if you want me to do that, or we could wait and see if the snyk check completes.

**Comment by kotodharma** [comment]
If this is not an urgent fix that needs to go in right away (it's not, right?) then let's wait and see how to get past this in a more "natural" way. One thing I don't understand right off the bat is why I am not able to bypass the checks and force a merge in my status as admin, the way I can do in the udaman repo. Any ideas about that?

**Comment by kotodharma** [comment]
Another thing I have a question about is the BitBucket webhooks that are configured for this repo and udaman and probly others. Are those just ancient and vestigial at this point, or are they in use? Any clue? I've never heard a word breathed about our having anything to do with BitBucket.

**Comment by vcward** [comment]
Yeah no problem, it's not urgent. I thought I saw a button to force merge before I added you as a reviewer, so it might only show up if no reviewer was requested? As for the bitbucket thing, I'm not sure. It looks related to our jira project? My guess is that's how Jira knows which branch is related to a particular issue, but that could be totally off.

**Pull request closed without merging**
